name: CentOS 7

on:
  pull_request:
  workflow_dispatch:

jobs:
  centos_7:
    name: PHP
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['74', '80', '81', '82']
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PHP and Build tools
        run: |
          yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
          yum update -y
          yum-config-manager --disable 'remi-php*' && yum-config-manager --enable remi-php${{ matrix.php-versions }}
          yum install git make gcc gcc-c++ binutils glibc-devel autoconf libtool bison re2c automake libxml2-devel sudo libuv-devel php-devel which php-pear -y
      - name: Build ext-uv
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make
          make install
          echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
