name: CentOS Stream

on:
  pull_request:
  workflow_dispatch:

jobs:
  stream_8:
    name: PHP
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PHP and Build tools
        run: |
          sed -i "s/mirrorlist/#mirrorlist/g" /etc/yum.repos.d/CentOS-*
          sed -i "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
          dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
          /usr/bin/crb enable
          dnf install centos-release-stream -y
          dnf swap centos-{linux,stream}-repos -y
          dnf distro-sync -y
          dnf update -y
          dnf install yum-utils -y
          dnf module reset php
          dnf module enable php:${{ matrix.php-versions }}
          dnf install https://rpmfind.net/linux/centos/8-stream/PowerTools/x86_64/os/Packages/libuv-devel-1.41.1-1.el8_4.x86_64.rpm -y
          dnf install sudo git php-devel libtool php-pear -y
      - name: Build ext-uv
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make
          make install
          echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
