name: CentOS 7

on:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        container:
        - {os: 'centos:7', cli: 'yum', dev: 'libuv-devel php-devel which', dep: 'yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-7.rpm', pre: "yum-config-manager --disable 'remi-php*' && yum-config-manager --enable remi-php"}
        php-versions: ['74', '80', '81', '82']
    runs-on: ubuntu-latest
    container: ${{ matrix.container.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PHP and Build tools
        run: |
          ${{ matrix.container.dep }} -y
          ${{ matrix.container.cli }} update -y
          ${{ matrix.container.pre }}${{ matrix.php-versions }}
          ${{ matrix.container.cli }} install sudo git ${{ matrix.container.dev }} libtool php-pear -y
      - name: Build ext-uv
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make
          make install
          echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
