name: Linux

on: [push, pull_request]

jobs:
  multi:
    name: ${{ matrix.operating-system }} CI - PHP ${{ matrix.php-versions }}-${{ matrix.threads }}
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        threads: [ts, nts]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
        env:
            phpts: ${{ matrix.threads }} # specify ts or nts
      - name: Install PHP Build tools
        run: |
          apt-get install libuv1-dev php-dev libtool php-pear -y
      - name: Build ext-uv nts
        if: matrix.threads == 'nts'
        run: |
            phpize
            ./configure --with-uv=$(readlink -f `pwd`/libuv)
            make
            make install
            echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Build ext-uv zts
        if: (matrix.threads == 'ts') && (matrix.php-versions != '7.4')
        run: |
            phpize
            ./configure --with-uv=$(readlink -f `pwd`/libuv) --enable-zts
            make
            make install
            echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Build ext-uv zts PHP 7.4
        if: (matrix.threads == 'ts') && (matrix.php-versions == '7.4')
        run: |
            phpize
            ./configure --with-uv=$(readlink -f `pwd`/libuv) --enable-maintainer-zts
            make
            make install
            echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: |
          php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
          ls
