name: Linux centos

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        container:
        - {os: 'centos:7', cli: 'yum', dev: 'libuv-devel php-devel which', dep: 'yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-7.rpm', pre: "yum-config-manager --disable 'remi-php*' && yum-config-manager --enable remi-php82"}
        - {os: 'centos:latest', cli: 'dnf', dev: 'libuv-devel php-devel which', dep: 'dnf --disablerepo "*" --enablerepo=extras swap centos-linux-repos centos-stream-repos && dnf distro-sync && dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm', pre: 'dnf module reset php && dnf module install php:remi-8.2 -y'}
    runs-on: ubuntu-latest
    container: ${{ matrix.container.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP and Build tools
        run: |
          ${{ matrix.container.dep }} -y
          ${{ matrix.container.cli }} update -y
          ${{ matrix.container.pre }}
          ${{ matrix.container.cli }} install sudo git ${{ matrix.container.dev }} libtool php-pear -y

      - name: Build ext-uv
        run: |
            phpize
            ./configure --with-uv=$(readlink -f `pwd`/libuv)
            make
            make install
            echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"

      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: |
          php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
          ls
