# GitHub Action for PHP with extensions
name: macOS

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        php-versions: ['8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8'
          tools: pecl
          extensions: curl, fileinfo, mbstring, openssl, simplexml, dom, sockets, sodium

      - name: Brew install
        run: |
          brew install automake

      - name: Build libuv
        run: |
          curl -L https://github.com/libuv/libuv/archive/v1.41.0.tar.gz | tar xzf -
          cd libuv-1.41.0
          sh autogen.sh
          ./configure
          make
          make check
          make install
          cd ..

      - name: Build ext-uv
        run: |
          phpize
          ./configure
          make
          make install
          echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"

      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: |
          php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
          ls
