name: Ubuntu

on:
  push:
    branches: [ 0.4x ]
  pull_request:
    branches: [ 0.4x ]
  workflow_dispatch:

jobs:
  multi:
    name: ${{ matrix.operating-system }} CI - PHP ${{ matrix.php-versions }}-${{ matrix.threads }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-22.04]
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        threads: [ts, nts]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php-versions }}
            coverage: none
        env:
            phpts: ${{ matrix.threads }} # specify ts or nts
      - name: Install libuv
        run: |
            sudo apt-get install libuv1-dev -y
      - name: Build ext-uv
        run: |
            phpize
            ./configure --with-uv=$(readlink -f `pwd`/libuv)
            make
            sudo make install
            echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Run tests
        env:
          NO_INTERACTION: 1
        run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
