# GitHub Action for PHP with extensions
name: Windows CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    defaults:
      run:
        shell: cmd
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['7.4', '8.0', '8.1', '8.2']
        arch: [x64]
        threads: [ts, nts]
        libuv: [ 1.44.2 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      id: setup-php
      uses: cmb69/setup-php-sdk@v0.7
      with:
        version: ${{matrix.version}}
        arch: ${{matrix.arch}}
        ts: ${{matrix.threads}}
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: Fetch & build libuv ${{matrix.libuv}} library dependency
      run: |
        curl -L https://github.com/libuv/libuv/archive/refs/tags/v${{matrix.libuv}}.zip --output libuv-${{matrix.libuv}}.zip
        unzip -xoq libuv-${{matrix.libuv}}.zip
        cd libuv-${{matrix.libuv}}
        cmake .
        msbuild INSTALL.vcxproj /p:Configuration=Release
        mkdir ..\..\deps\include\uv
        mkdir ..\..\deps\lib
        mkdir ..\..\deps\bin
        copy /Y include\uv\* ..\..\deps\include\uv\
        copy /Y include\* ..\..\deps\include\
        copy /Y Release\uv_a.lib ..\..\deps\lib\
        copy /Y Release\uv.lib ..\..\deps\lib\
        copy /Y Release\uv.exp ..\..\deps\lib\
        copy /Y Release\uv.dll ..\..\deps\bin\
        cd ..
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}
        toolset: ${{steps.setup-php.outputs.toolset}}
    - name: phpize
      run: phpize
    - name: configure
      run: configure --with-uv --enable-debug-pack --with-prefix=${{steps.setup-php.outputs.prefix}}
    - name: make
      run: nmake
    - name: test
      run: |
        copy /Y ..\deps\bin\uv.dll php-bin\libuv.dll
        copy /Y ..\deps\bin\uv.dll \php\libuv.dll
        dir .
        dir ..
        dir php-bin
        if "${{matrix.threads}}" == "ts" (
            copy /Y x64\Release_TS\php_uv.dll php-bin\ext\php_uv.dll
            copy /Y x64\Release_TS\php_uv.dll \php\ext\php_uv.dll
        ) else if "${{matrix.threads}}" == "nts" (
            copy /Y x64\Release\php_uv.dll php-bin\ext\php_uv.dll
            copy /Y x64\Release\php_uv.dll \php\ext\php_uv.dll
        )
        dir x64
        copy /Y php-bin\php.ini-production php-bin\php.ini
        echo extension=uv >> php-bin\php.ini
        cd php-bin\
        php.exe -m
        php.exe -v
        \php\ext\php.exe -v
        nmake test TESTS="--show-diff tests"
