# GitHub Action for PHP with extensions
name: Windows PHP 8+ Release

on:
  release:
    types: [published]

jobs:
  windows:
    name: Windows
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0.28', '8.1.17', '8.2.4']
        thread: [nts, ts]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build PHP ${{ matrix.php }}-${{ matrix.thread }} with libuv and ext-uv
      run: .\cmd\compile_x64.bat --php ${{ matrix.php }} --${{ matrix.thread }} --shared
    - name: Create binary archive from release
      run: |
        if "${{matrix.thread}}" == "ts" (
            copy /Y php-sdk\phpdev\vs16\x64\php-${{matrix.php}}\x64\Release_TS\pecl-${{matrix.php}}\php_uv.dll php_uv.dll
            copy /Y php-sdk\phpdev\vs16\x64\php-${{matrix.php}}\x64\Release_TS\php-${{matrix.php}}\uv.dll uv.dll
        ) else if "${{matrix.thread}}" == "nts" (
            copy /Y php-sdk\phpdev\vs16\x64\php-${{matrix.php}}\x64\Release\pecl-${{matrix.php}}\php_uv.dll php_uv.dll
            copy /Y php-sdk\phpdev\vs16\x64\php-${{matrix.php}}\x64\Release\php-${{matrix.php}}\uv.dll uv.dll
        )
        7z a ext_uv-${{ github.event.release.tag_name }}-${{matrix.php}}-${{ matrix.thread }}-vs16-x64.zip uv.dll php_uv.dll -tzip -y
    - name: Upload the windows binary artifacts
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ext_uv-${{ github.event.release.tag_name }}-${{matrix.php}}-${{ matrix.thread }}-vs16-x64.zip
          asset_name: ext_uv-${{ github.event.release.tag_name }}-${{matrix.php}}-${{ matrix.thread }}-vs16-x64
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Windows binary - uv.dll and php_uv.dll "
