# GitHub Action for PHP with extensions
name: Windows

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0.7', '8.1.0alpha1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build PHP 8-NTS with libuv and ext-uv
      run: .\cmd\compile_x64.cmd --php ${{ matrix.php }}

    - name: Run tests
      shell: cmd
      run: .\cmd\windows_run_test.cmd --php ${{ matrix.php }}

  windows_ts:
    name: Windows Thread Safe
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0.7', '8.1.0alpha1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build PHP 8-TS with libuv and ext-uv
      run: .\cmd\compile_x64-ts.cmd --php ${{ matrix.php }}

    - name: Run tests
      run: .\cmd\windows_run_test-ts.cmd --php ${{ matrix.php }}
